name: Dialyzer

on: push

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  Dialyzer:
    runs-on: ubuntu-latest

    env:
      MIX_ENV: test

    steps:
      - uses: actions/checkout@v2

      - name: Set up Elixir
        uses: erlef/setup-beam@v1
        with:
          elixir-version: '1.14.1' # Define the elixir version [required]
          otp-version: '25.1.2' # Define the OTP version [required]


      - name: Install Rebar & Hex
        run: mix local.hex --force && mix local.rebar --force

      - name: Restore dependencies cache
        uses: actions/cache@v3
        with:
          path: |
                _build
                deps
                .check
          key: ${{ runner.os }}-mix-${{ hashFiles('**/mix.lock') }}-${{ hashFiles('./.tool-versions') }}
          restore-keys: ${{ runner.os }}-mix-

      - name: Install Dependencies
        run: mix deps.get

      - name: Compile Project
        run: mix compile

      - name: Run Dialyzer
        run: mkdir -p .check && mix dialyzer


